# Generated by Django 4.2.3 on 2023-07-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notlarim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorumlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar', models.CharField(max_length=100)),
                ('icerik', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('notlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='notlarim.notlar')),
            ],
        ),
    ]
