# Generated by Django 4.2.3 on 2023-07-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notlarim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notlar',
            name='ekleme_tarihi',
        ),
        migrations.RemoveField(
            model_name='notlar',
            name='yazar',
        ),
    ]
