# Generated by Django 4.2.3 on 2023-07-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notlarim', '0003_notlar_author_notlar_date_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notlar',
            name='author',
        ),
        migrations.RemoveField(
            model_name='notlar',
            name='date',
        ),
    ]
